version: '3'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    env_file:
      - .env

  app: &app
    image: tpass_app
    build:
      context: .
      dockerfile: ./docker/backend/local/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - ./docs:/docs
      - ./shared/media:/app/shared/media
      - ./shared/static:/app/shared/static
      - ./shared/templates:/app/shared/templates

  web:
    image: tpass_web
    build:
      context: .
      dockerfile: ./docker/frontend/local/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
