# Generated by Django 2.0.9 on 2018-11-01 14:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('init_date', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField()),
            ],
        ),
    ]
