# Generated by Django 2.0.9 on 2018-11-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Transaction initialized'), (2, 'Transaction approved'), (3, 'Transaction rejected')], default=1),
        ),
    ]
